#
# Table structure for table 'tx_brwkunden_domain_model_kundendaten'
#
CREATE TABLE tx_brwkunden_domain_model_kundendaten (

	uid int(11) NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,

	erstellt varchar(255) DEFAULT '' NOT NULL,
  user varchar(255) DEFAULT '' NOT NULL,
	projekt varchar(255) DEFAULT '' NOT NULL,
	bauart varchar(255) DEFAULT '' NOT NULL,
	gebaeudeart varchar(255) DEFAULT '' NOT NULL,
	kategorie varchar(255) DEFAULT '' NOT NULL,
	plzbau varchar(255) DEFAULT '' NOT NULL,
	lkzbau varchar(255) DEFAULT '' NOT NULL,
	ortbau varchar(255) DEFAULT '' NOT NULL,
	strbau varchar(255) DEFAULT '' NOT NULL,
	bl varchar(255) DEFAULT '' NOT NULL,
	lkr varchar(255) DEFAULT '' NOT NULL,
	planstand varchar(255) DEFAULT '' NOT NULL,
	gepl_bau_beg varchar(255) DEFAULT '' NOT NULL,
	gepl_bauzeit varchar(255) DEFAULT '' NOT NULL,
	mauerwerk varchar(255) DEFAULT '' NOT NULL,
	dachkonstr varchar(255) DEFAULT '' NOT NULL,
	dacheind varchar(255) DEFAULT '' NOT NULL,
	fassade varchar(255) DEFAULT '' NOT NULL,
	sonst_baudet varchar(255) DEFAULT '' NOT NULL,
	ausstatt_aussen varchar(255) DEFAULT '' NOT NULL,
	ausstatt_innen varchar(255) DEFAULT '' NOT NULL,
	gewerk_vorber varchar(255) DEFAULT '' NOT NULL,
	gewerk_aussenanlage varchar(255) DEFAULT '' NOT NULL,
	allg_gewerk varchar(255) DEFAULT '' NOT NULL,
	dl_gewerke varchar(255) DEFAULT '' NOT NULL,
	vergabe_kz varchar(255) DEFAULT '' NOT NULL,
	bh_funktion varchar(255) DEFAULT '' NOT NULL,
	bh_adressnr varchar(255) DEFAULT '' NOT NULL,
	b_h_name varchar(255) DEFAULT '' NOT NULL,
	bhlkz varchar(255) DEFAULT '' NOT NULL,
	bh_plz varchar(255) DEFAULT '' NOT NULL,
	bh_ort varchar(255) DEFAULT '' NOT NULL,
	bh_str varchar(255) DEFAULT '' NOT NULL,
	bh_tel varchar(255) DEFAULT '' NOT NULL,
	bh_fax varchar(255) DEFAULT '' NOT NULL,
	bh_mail varchar(255) DEFAULT '' NOT NULL,
	bh_zust varchar(255) DEFAULT '' NOT NULL,
	direkt_telbh varchar(255) DEFAULT '' NOT NULL,
	bh_direkt_fax varchar(255) DEFAULT '' NOT NULL,
	bh_direkt_mail varchar(255) DEFAULT '' NOT NULL,
	bh_homepage varchar(255) DEFAULT '' NOT NULL,
	bh_handy varchar(255) DEFAULT '' NOT NULL,
	bu_funktion varchar(255) DEFAULT '' NOT NULL,
	bu_adress_nr varchar(255) DEFAULT '' NOT NULL,
	bu_name varchar(255) DEFAULT '' NOT NULL,
	bu_plz varchar(255) DEFAULT '' NOT NULL,
	bu_ort varchar(255) DEFAULT '' NOT NULL,
	bu_str varchar(255) DEFAULT '' NOT NULL,
	bu_tel varchar(255) DEFAULT '' NOT NULL,
	bu_fax varchar(255) DEFAULT '' NOT NULL,
	bu_mail varchar(255) DEFAULT '' NOT NULL,
	buzust_a_p varchar(255) DEFAULT '' NOT NULL,
	budirekt_tel varchar(255) DEFAULT '' NOT NULL,
	bu_direkt_fax varchar(255) DEFAULT '' NOT NULL,
	budirekt_mail varchar(255) DEFAULT '' NOT NULL,
	buwebsite varchar(255) DEFAULT '' NOT NULL,
	bu_handy varchar(255) DEFAULT '' NOT NULL,
	ar_funktion_arch varchar(255) DEFAULT '' NOT NULL,
	ar_adressnr varchar(255) DEFAULT '' NOT NULL,
	ar_name varchar(255) DEFAULT '' NOT NULL,
	ar_p_l_z varchar(255) DEFAULT '' NOT NULL,
	ar_ort varchar(255) DEFAULT '' NOT NULL,
	ar_str varchar(255) DEFAULT '' NOT NULL,
	ar_tel varchar(255) DEFAULT '' NOT NULL,
	ar_fax varchar(255) DEFAULT '' NOT NULL,
	ar_mail varchar(255) DEFAULT '' NOT NULL,
	arzust_a_p varchar(255) DEFAULT '' NOT NULL,
	ar_direkt_tel varchar(255) DEFAULT '' NOT NULL,
	ardirekt_fax varchar(255) DEFAULT '' NOT NULL,
	ardirekt_mail varchar(255) DEFAULT '' NOT NULL,
	ar_website varchar(255) DEFAULT '' NOT NULL,
	ar_handy varchar(255) DEFAULT '' NOT NULL,
	called_on varchar(255) DEFAULT '' NOT NULL,
	recall varchar(255) DEFAULT '' NOT NULL,
	notice text NOT NULL,
	proirity int(11) DEFAULT '0' NOT NULL,
  hiderecord tinyint(4) unsigned DEFAULT '0' NOT NULL,
	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
	crdate int(11) unsigned DEFAULT '0' NOT NULL,
	cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
	starttime int(11) unsigned DEFAULT '0' NOT NULL,
	endtime int(11) unsigned DEFAULT '0' NOT NULL,

	t3ver_oid int(11) DEFAULT '0' NOT NULL,
	t3ver_id int(11) DEFAULT '0' NOT NULL,
	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
	t3ver_label varchar(255) DEFAULT '' NOT NULL,
	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_stage int(11) DEFAULT '0' NOT NULL,
	t3ver_count int(11) DEFAULT '0' NOT NULL,
	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
	t3ver_move_id int(11) DEFAULT '0' NOT NULL,
	sorting int(11) DEFAULT '0' NOT NULL,
	t3_origuid int(11) DEFAULT '0' NOT NULL,
	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumblob,

	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY t3ver_oid (t3ver_oid,t3ver_wsid),
	KEY language (l10n_parent,sys_language_uid)

);